GET /api/contacts
Host: 54.206.118.54:8080
Accept: application/xml

###

http://54.206.118.54:8080/images/men/65.jpeg

###

GET /api/contacts
Host: 54.206.118.54:8080
Accept: application/json

###
GET /api/contacts/1ede412e-bb8c-4f6b-b187-49ac4e8abadd
Host: 54.206.118.54:8080
Accept: application/json

###
GET /api/contacts/1ede412e-bb8c-4f6b-b187-49ac4e8abadd
Host: 54.206.118.54:8080
Accept: application/xml

###
GET /api/contacts/1ede412e-bb8c-4f6b-b187-49ac4e8abadd
Host: 54.206.118.54:8080
Accept: text/plain

###
POST /api/contacts
Host: 54.206.118.54:8080
Accept: application/json
Content-Type: application/json

{
    "firstname": "Vinod",
    "email": "vinod@vinod.co",
    "phone": "9731424784"
}

###